### ISSUE TITLE
issue at signup. any way to change it to phpmailer instead of smtp?

### ISSUE THREAD

**Issue by stewie27** [subins2000/open#17]
a4pT2clC%2FFFqrskY%2FRvHvUmU%2B%2B7jr3%2BZh3VCfiJQAXahm%2FMnaBJhzYvxLF%2BqP3Nywc20qMtNjtxEf3an7Jq9tA%3D%3DSMTP Error: Could not authenticate.
Error

Something happenned while sending verification code. Try again for atleast 6 times and if it didn't work, post the issue on GitHub

**Comment by subins2000** [comment]
Currently, Open is using PHPMailer to send emails. And GMail SMTP is used to send emails. As it is made using PHPMailer, it can be changed to any method.
https://github.com/subins2000/open/blob/master/inc/class.open.php#L583

**Comment by stewie27** [comment]
i understand that i have to use my credentuals for smtp but wanted to run it with phpmailer at the moment before setting up smtp just not sure how :/

**Comment by subins2000** [comment]
I don't know what you mean by "run it with phpmailer". It is using PHPMailer Library to send emails. Do you mean to send emails using PHP's "mail()" function ?

**Comment by stewie27** [comment]
yeah sorry i always refer to mail() as phpmailer :/
but yeah is it doable to setup the mail() function for the time been?

**Comment by subins2000** [comment]
Yes, you can modify the contents inside **\Open::sendEMail()** function to PHP's mail() with parameters accordingly.
https://github.com/subins2000/open/blob/master/inc/class.open.php#L533
